const text = new Map()
text.set('視頻', '影片')
text.set('视频', '影片')
text.set('葱宝', '蔥宝')
text.set('洋葱', '洋蔥')
text.set('注', '註')
text.set('賬戶', '帳號')
text.set('從新觀看', '重新觀看')
text.set('全國', '中國大陸')
text.set('中國', '中國大陸')
text.set('壹家', '一家')
text.set('專註', '專注')
text.set('壹切', '一切')
text.set('註意', '注意')
text.set('幹擾', '干擾')
text.set('復制', '複製')
text.set('一周內', '一週內')
text.set('全屏', '螢幕')
text.set('标', '標')
text.set('标', '標')
module.exports = text
